export interface FallbackProduct {
  id: string;
  title: string;
  price: number;
  description: string;
  category: string;
  categoryId: string;
  imageUrl: string;
  images: string[];
  city: string;
  location: string;
  postedAt: string;
  condition: string;
  featured?: boolean;
  badge?: string;
  badgeText?: string;
  views: number;
  status: string;
  seller: {
    id: string;
    name: string;
    phone?: string;
    avatarUrl?: string;
    memberSince: string;
    rating: number;
    verified: boolean;
  };
}

export const FALLBACK_PRODUCTS: FallbackProduct[] = [
  {
    id: 'prod-1',
    title: 'Maruti Swift 2019',
    price: 450000,
    description: 'Single owner, pristine condition, full service history at authorized Maruti center. Driven 42,000 km. Comprehensive insurance valid till Dec 2026.',
    category: 'cars',
    categoryId: 'cat-cars',
    imageUrl: '/images/car_red.jpg',
    images: ['/images/car_red.jpg'],
    city: 'Chennai',
    location: 'Chennai • 2 hours ago',
    postedAt: '2 hours ago',
    condition: 'Like New',
    featured: true,
    badge: 'featured',
    badgeText: 'Featured',
    views: 142,
    status: 'active',
    seller: {
      id: 'usr-1',
      name: 'Karthik Raja',
      phone: '+91 98401 23456',
      memberSince: 'Mar 2023',
      rating: 4.9,
      verified: true,
    },
  },
  {
    id: 'prod-2',
    title: 'Yamaha FZ',
    price: 85000,
    description: '2021 model, matte black edition, very well maintained. New rear tyre and recently serviced. Complete documentation available.',
    category: 'bikes',
    categoryId: 'cat-bikes',
    imageUrl: '/images/bike_yamaha.jpg',
    images: ['/images/bike_yamaha.jpg'],
    city: 'Chennai',
    location: 'Chennai • 4 hours ago',
    postedAt: '4 hours ago',
    condition: 'Excellent',
    featured: true,
    badge: 'featured',
    badgeText: 'Featured',
    views: 98,
    status: 'active',
    seller: {
      id: 'usr-2',
      name: 'Vignesh M',
      phone: '+91 97910 88231',
      memberSince: 'Jan 2024',
      rating: 4.8,
      verified: true,
    },
  },
  {
    id: 'prod-3',
    title: 'iPhone 14 Pro 128GB',
    price: 68000,
    description: 'Deep Purple, 89% battery health. Comes with original box, Apple invoice, and unused cable. No scratches or dents.',
    category: 'mobiles',
    categoryId: 'cat-mobiles',
    imageUrl: '/images/phone_purple.jpg',
    images: ['/images/phone_purple.jpg'],
    city: 'Chennai',
    location: 'Chennai • 5 hours ago',
    postedAt: '5 hours ago',
    condition: 'Like New',
    featured: true,
    badge: 'trending',
    badgeText: 'Hot Deal',
    views: 230,
    status: 'active',
    seller: {
      id: 'usr-3',
      name: 'Suresh Kumar',
      phone: '+91 94441 55210',
      memberSince: 'Nov 2022',
      rating: 5.0,
      verified: true,
    },
  },
  {
    id: 'prod-4',
    title: 'MacBook Pro M2 14"',
    price: 135000,
    description: '16GB RAM, 512GB SSD, Space Gray. Only 45 battery cycles. AppleCare+ valid till Aug 2026. Perfect for creators and devs.',
    category: 'electronics',
    categoryId: 'cat-electronics',
    imageUrl: '/images/laptop_macbook.jpg',
    images: ['/images/laptop_macbook.jpg'],
    city: 'Chennai',
    location: 'Chennai • 6 hours ago',
    postedAt: '6 hours ago',
    condition: 'Brand New',
    featured: true,
    badge: 'featured',
    badgeText: 'Top Pick',
    views: 312,
    status: 'active',
    seller: {
      id: 'usr-4',
      name: 'Ananya Ramesh',
      phone: '+91 98840 76543',
      memberSince: 'Jun 2023',
      rating: 4.9,
      verified: true,
    },
  },
  {
    id: 'prod-5',
    title: 'Golden Retriever Puppies',
    price: 22000,
    description: 'KCI certified Golden Retriever puppies, 55 days old. Dewormed and first vaccination completed. Very active and healthy.',
    category: 'pets',
    categoryId: 'cat-pets',
    imageUrl: '/images/pet.jpg',
    images: ['/images/pet.jpg'],
    city: 'Chennai',
    location: 'Chennai • 1 day ago',
    postedAt: '1 day ago',
    condition: 'Healthy',
    featured: false,
    views: 184,
    status: 'active',
    seller: {
      id: 'usr-10',
      name: 'Dr. Pet Haven',
      phone: '+91 98111 22334',
      memberSince: 'May 2023',
      rating: 4.9,
      verified: true,
    },
  },
  {
    id: 'prod-6',
    title: '2 BHK Apartment in Velachery',
    price: 6500000,
    description: '1050 sq.ft, East facing, 2nd floor with covered car parking and lift. Ready to occupy. 500m from Velachery MRTS station.',
    category: 'properties',
    categoryId: 'cat-properties',
    imageUrl: '/images/apartment.jpg',
    images: ['/images/apartment.jpg'],
    city: 'Chennai',
    location: 'Chennai • 8 hours ago',
    postedAt: '8 hours ago',
    condition: 'Ready to Move',
    featured: true,
    badge: 'verified',
    badgeText: 'Verified',
    views: 420,
    status: 'active',
    seller: {
      id: 'usr-6',
      name: 'Apex Realtors',
      phone: '+91 98410 99882',
      memberSince: 'Jan 2022',
      rating: 4.7,
      verified: true,
    },
  },
  {
    id: 'prod-7',
    title: 'Wooden Dining Table (6 Seater)',
    price: 18500,
    description: 'Solid Sheesham wood 6-seater dining table with glass top and 6 cushioned chairs. Excellent condition, moving out sale.',
    category: 'furniture',
    categoryId: 'cat-furniture',
    imageUrl: '/images/sofa_brown.jpg',
    images: ['/images/sofa_brown.jpg'],
    city: 'Chennai',
    location: 'Chennai • 10 hours ago',
    postedAt: '10 hours ago',
    condition: 'Good',
    featured: false,
    views: 87,
    status: 'active',
    seller: {
      id: 'usr-5',
      name: 'Deepak Nathan',
      phone: '+91 99620 11984',
      memberSince: 'Aug 2023',
      rating: 4.6,
      verified: false,
    },
  },
  {
    id: 'prod-8',
    title: 'Sony Alpha A7 III Camera',
    price: 98000,
    description: 'Body with 28-70mm lens, 2 original Sony batteries, 64GB Extreme Pro card, and bag. Shutter count under 12,000.',
    category: 'electronics',
    categoryId: 'cat-electronics',
    imageUrl: '/images/camera.jpg',
    images: ['/images/camera.jpg'],
    city: 'Chennai',
    location: 'Chennai • 12 hours ago',
    postedAt: '12 hours ago',
    condition: 'Like New',
    featured: true,
    badge: 'featured',
    badgeText: 'Pro Gear',
    views: 275,
    status: 'active',
    seller: {
      id: 'usr-7',
      name: 'Pravin Studio',
      phone: '+91 91760 33419',
      memberSince: 'Feb 2023',
      rating: 5.0,
      verified: true,
    },
  },
];
