import { Product } from '../types/product.types';
import { Category } from '../types/category.types';

export const CITIES = [
  'Chennai',
  'Bangalore',
  'Mumbai',
  'Delhi NCR',
  'Hyderabad',
  'Pune',
  'Kolkata',
];

export const CATEGORIES: Category[] = [
  { id: 'cars', name: 'Cars', slug: 'cars', imageUrl: '/images/car_red.png', itemCount: 42, featured: true },
  { id: 'bikes', name: 'Bikes', slug: 'bikes', imageUrl: '/images/bike_yamaha.png', itemCount: 28, featured: true },
  { id: 'mobiles', name: 'Mobiles', slug: 'mobiles', imageUrl: '/images/phone_purple.png', itemCount: 65, featured: true },
  { id: 'laptops', name: 'Laptops & Computers', slug: 'laptops', imageUrl: '/images/laptop_macbook.png', itemCount: 34, featured: true },
  { id: 'properties', name: 'Properties', slug: 'properties', imageUrl: '/images/apartment.png', itemCount: 19, featured: true },
  { id: 'furniture', name: 'Furniture', slug: 'furniture', imageUrl: '/images/sofa_brown.png', itemCount: 53, featured: true },
  { id: 'electronics', name: 'Electronics', slug: 'electronics', imageUrl: '/images/camera.png', itemCount: 37, featured: true },
  { id: 'fashion', name: 'Fashion', slug: 'fashion', imageUrl: '/images/fashion.png', itemCount: 88, featured: true },
  { id: 'pets', name: 'Pets', slug: 'pets', imageUrl: '/images/pet.png', itemCount: 15, featured: true },
  { id: 'books', name: 'Books & Hobbies', slug: 'books', imageUrl: '/images/books.png', itemCount: 40, featured: true },
  { id: 'services', name: 'Services', slug: 'services', imageUrl: '/images/services.png', itemCount: 22, featured: true },
  { id: 'jobs', name: 'Jobs', slug: 'jobs', imageUrl: '/images/jobs.png', itemCount: 14, featured: true },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Maruti Swift 2019',
    price: 450000,
    description: 'Single owner, pristine condition, full service history at authorized Maruti center. Driven 42,000 km. Comprehensive insurance valid till Dec 2026.',
    category: 'cars',
    categoryId: 'cars',
    imageUrl: '/images/car_red.jpg',
    images: ['/images/car_red.jpg'],
    city: 'Chennai',
    location: 'Chennai • 2 hours ago',
    postedAt: '2 hours ago',
    condition: 'Like New',
    featured: true,
    badge: 'featured',
    badgeText: 'Featured',
    views: 142,
    status: 'active',
    seller: {
      id: 'usr-1',
      name: 'Karthik Raja',
      phone: '+91 98401 23456',
      memberSince: 'Mar 2023',
      rating: 4.9,
      verified: true,
    }
  },
  {
    id: 'prod-2',
    title: 'Yamaha FZ',
    price: 85000,
    description: 'Yamaha FZ Version 3.0 in racing blue. Brand new rear Michelin tire, smooth engine, no accident history. All papers clear.',
    category: 'bikes',
    categoryId: 'bikes',
    imageUrl: '/images/bike_yamaha.jpg',
    images: ['/images/bike_yamaha.jpg'],
    city: 'Chennai',
    location: 'Chennai • 5 hours ago',
    postedAt: '5 hours ago',
    condition: 'Good',
    featured: true,
    badge: 'good',
    badgeText: 'Good Condition',
    views: 98,
    status: 'active',
    seller: {
      id: 'usr-2',
      name: 'Vignesh M',
      phone: '+91 97910 88231',
      memberSince: 'Jan 2024',
      rating: 4.8,
      verified: true,
    }
  },
  {
    id: 'prod-3',
    title: 'iPhone 13 128GB',
    price: 28000,
    description: 'iPhone 13 128GB Midnight Purple, 89% battery health. Comes with original box, braided lightning cable, and Spigen protective case.',
    category: 'mobiles',
    categoryId: 'mobiles',
    imageUrl: '/images/phone_purple.jpg',
    images: ['/images/phone_purple.jpg'],
    city: 'Chennai',
    location: 'Chennai • 1 day ago',
    postedAt: '1 day ago',
    condition: 'Like New',
    featured: true,
    badge: 'likenew',
    badgeText: 'Like New',
    views: 310,
    status: 'active',
    seller: {
      id: 'usr-3',
      name: 'Suresh Kumar',
      phone: '+91 94441 55210',
      memberSince: 'Nov 2022',
      rating: 5.0,
      verified: true,
    }
  },
  {
    id: 'prod-4',
    title: '3 Seater Sofa',
    price: 12000,
    description: 'Premium rich brown genuine leatherette 3-seater sofa. Ergonomic cushioned back, sturdy solid wood frame. Pet-free and smoke-free home.',
    category: 'furniture',
    categoryId: 'furniture',
    imageUrl: '/images/sofa_brown.jpg',
    images: ['/images/sofa_brown.jpg'],
    city: 'Chennai',
    location: 'Chennai • 1 day ago',
    postedAt: '1 day ago',
    condition: 'Good',
    featured: false,
    views: 84,
    status: 'active',
    seller: {
      id: 'usr-4',
      name: 'Ananya Ramesh',
      phone: '+91 98840 76543',
      memberSince: 'Aug 2023',
      rating: 4.7,
      verified: true,
    }
  },
  {
    id: 'prod-5',
    title: 'MacBook Air M1 (256GB SSD)',
    price: 45000,
    description: 'Apple MacBook Air M1 (2020), 8GB RAM, 256GB SSD, Space Gray. 94% Battery Health (112 cycles). Spotless body, always used with screen protector.',
    category: 'electronics',
    categoryId: 'electronics',
    imageUrl: '/images/laptop_macbook.jpg',
    images: ['/images/laptop_macbook.jpg'],
    city: 'Chennai',
    location: 'Chennai • 2 days ago',
    postedAt: '2 days ago',
    condition: 'Like New',
    featured: true,
    badge: 'featured',
    badgeText: 'Featured',
    views: 420,
    status: 'active',
    seller: {
      id: 'usr-5',
      name: 'Deepak Nathan',
      phone: '+91 99620 11984',
      memberSince: 'Feb 2022',
      rating: 4.9,
      verified: true,
    }
  },
  {
    id: 'prod-6',
    title: '2 BHK Luxury Apartment',
    price: 7500000,
    description: 'Spacious 2 BHK gated community apartment, 1150 sq.ft, south-facing, covered car parking, 24/7 power backup, swimming pool, gym, clubhouse.',
    category: 'properties',
    categoryId: 'properties',
    imageUrl: '/images/apartment.jpg',
    images: ['/images/apartment.jpg'],
    city: 'Chennai',
    location: 'Chennai • 3 days ago',
    postedAt: '3 days ago',
    condition: 'Brand New',
    featured: true,
    badge: 'verified',
    badgeText: 'Verified',
    views: 560,
    status: 'active',
    seller: {
      id: 'usr-6',
      name: 'Apex Realtors',
      phone: '+91 98410 99882',
      memberSince: 'Jul 2021',
      rating: 4.8,
      verified: true,
    }
  },
  {
    id: 'prod-7',
    title: 'Canon EOS 1500D DSLR + 18-55mm',
    price: 24500,
    description: 'Canon EOS 1500D DSLR with 18-55mm IS STM Lens kit, 64GB Extreme SD Card, original battery, charger, neck strap, and camera bag.',
    category: 'electronics',
    categoryId: 'electronics',
    imageUrl: '/images/camera.jpg',
    images: ['/images/camera.jpg'],
    city: 'Chennai',
    location: 'Chennai • 4 hours ago',
    postedAt: '4 hours ago',
    condition: 'Like New',
    featured: false,
    badge: 'likenew',
    badgeText: 'Like New',
    views: 112,
    status: 'active',
    seller: {
      id: 'usr-7',
      name: 'Pravin Studio',
      phone: '+91 91760 33419',
      memberSince: 'Oct 2023',
      rating: 4.9,
      verified: true,
    }
  },
  {
    id: 'prod-8',
    title: 'Royal Enfield Classic 350',
    price: 135000,
    description: 'Royal Enfield Classic 350 Stealth Black edition. Dual-channel ABS, aftermarket alloy wheels, smooth thump, insured till 2027.',
    category: 'bikes',
    categoryId: 'bikes',
    imageUrl: '/images/bike_yamaha.jpg',
    images: ['/images/bike_yamaha.jpg'],
    city: 'Chennai',
    location: 'Chennai • 6 hours ago',
    postedAt: '6 hours ago',
    condition: 'Good',
    featured: false,
    views: 230,
    status: 'active',
    seller: {
      id: 'usr-8',
      name: 'Balaji S',
      phone: '+91 90030 45612',
      memberSince: 'May 2023',
      rating: 4.6,
      verified: true,
    }
  },
  {
    id: 'prod-9',
    title: 'Pure Leather Rider Jacket (M)',
    price: 3200,
    description: 'Genuine heavy-duty motorcycle riding leather jacket, size L. Removable CE approved armors on shoulders and elbows. Thermal inner lining.',
    category: 'fashion',
    categoryId: 'fashion',
    imageUrl: '/images/fashion.jpg',
    images: ['/images/fashion.jpg'],
    city: 'Chennai',
    location: 'Chennai • 1 day ago',
    postedAt: '1 day ago',
    condition: 'Good',
    featured: false,
    badge: 'brandnew',
    badgeText: 'Brand New',
    views: 75,
    status: 'active',
    seller: {
      id: 'usr-9',
      name: 'Gowtham R',
      phone: '+91 95001 77234',
      memberSince: 'Nov 2023',
      rating: 4.7,
      verified: true,
    }
  },
  {
    id: 'prod-10',
    title: 'Premium Pet Bed & Leash Set',
    price: 1800,
    description: 'Orthopedic memory foam dog bed (medium/large size) + heavy duty reflective padded leash with harness. Machine washable cover, brand new.',
    category: 'pets',
    categoryId: 'pets',
    imageUrl: '/images/pet.jpg',
    images: ['/images/pet.jpg'],
    city: 'Chennai',
    location: 'Chennai • 2 days ago',
    postedAt: '2 days ago',
    condition: 'Brand New',
    featured: false,
    views: 64,
    status: 'active',
    seller: {
      id: 'usr-10',
      name: 'Pooja V',
      phone: '+91 98402 33119',
      memberSince: 'Dec 2023',
      rating: 5.0,
      verified: true,
    }
  },
  {
    id: 'prod-11',
    title: 'Algorithms & JS Handbook Set',
    price: 950,
    description: 'Bundle of 3 computer science and web development books including Grokking Algorithms, Eloquent JavaScript, and You Don\'t Know JS.',
    category: 'books',
    categoryId: 'books',
    imageUrl: '/images/books.jpg',
    images: ['/images/books.jpg'],
    city: 'Chennai',
    location: 'Chennai • 3 days ago',
    postedAt: '3 days ago',
    condition: 'Good',
    featured: false,
    views: 92,
    status: 'active',
    seller: {
      id: 'usr-11',
      name: 'Aravind S',
      phone: '+91 96000 88712',
      memberSince: 'Apr 2024',
      rating: 4.8,
      verified: true,
    }
  },
  {
    id: 'prod-12',
    title: 'Deep Home Sanitization Service',
    price: 1499,
    description: 'Professional hospital-grade disinfectant fogging and sanitization service for 2BHK/3BHK flats. Eco-friendly, pet-safe chemicals.',
    category: 'services',
    categoryId: 'services',
    imageUrl: '/images/services.jpg',
    images: ['/images/services.jpg'],
    city: 'Chennai',
    location: 'Chennai • Just now',
    postedAt: 'Just now',
    condition: 'Brand New',
    featured: false,
    badge: 'verified',
    badgeText: 'Verified',
    views: 48,
    status: 'active',
    seller: {
      id: 'usr-12',
      name: 'CleanPro Services',
      phone: '+91 98415 67890',
      memberSince: 'Jan 2023',
      rating: 4.9,
      verified: true,
    }
  },
];
